config/routes.rb
Rails.application.routes.draw do
  get 'lectures/create'
  get 'lectures/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  get 'mangas/index'
  get 'mangas/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :mangas do
    resources :chapitres, only: [:show] do
      resources :lectures, only: [:create, :destroy]
      # resources :bookmarks, only: [:create]
    end
    resources :bookmarks, only: [:create]
  end
  resources :lists, only: [:index, :show, :create, :destroy] do
    resources :bookmarks, only: [:destroy]
  end
  resources :lectures, only: [:destroy]
  resources :users, only: [:show]
end

# resources :search, only: [:index] # For search feature (Algolia)
# resources :comments, only: [:create, :destroy]
# resources :notifications, only: [:index, :destroy] # For notifications



# Defines the root path route ("/")
# root "posts#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :manga
  belongs_to :list
end

app/models/chapitre.rb
class Chapitre < ApplicationRecord
  belongs_to :manga
  has_many :lectures, dependent: :destroy
  has_many :users, through: :lectures

end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :user
  belongs_to :chapitre

  validates :lu, inclusion: { in: [true, false] }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :chapitres, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many  :lectures, dependent: :destroy
  has_many  :chapitres, through: :lectures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chapitres_controller.rb
class ChapitresController < ApplicationController
  def mark_as_read
    @chapitre = Chapitre.find(params[:id])
    @manga = @chapitre.manga
    @manga.update(lu_chapitres: @manga.lu_chapitres + [@chapitre.numero])
    respond_to do |format|
      format.js
    end
  end

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def create
    @manga = Manga.find(params[:manga_id])
    @chapitre = Chapitre.find(params[:chapitre_id])
    @lecture = Lecture.new(user: current_user, chapitre: @chapitre)
    if @lecture.save
      redirect_to manga_chapitre_path(@manga, @chapitre)
    else
      render 'chapitres/show'
    end
  end

  def destroy
  end

  # app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def mark_as_read
    chapitre_id = params[:chapitre_id]
    current_user.lectures.find_or_create_by(chapitre_id: chapitre_id).update(lu: true)
    redirect_back fallback_location: root_path
  end

  def mark_as_unread
    chapitre_id = params[:chapitre_id]
    current_user.lectures.find_or_create_by(chapitre_id: chapitre_id).update(lu: false)
    redirect_back fallback_location: root_path
  end
end

end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  def index
    @mangas = Manga.all

    if params[:query].present?
      sql_subquery= <<~SQL
        nom ILIKE :query
        OR auteur ILIKE :query
        OR synopsys ILIKE :query
        OR statut ILIKE :query
      SQL
      @mangas = Manga.where(sql_subquery, query: "%#{params[:query]}%")
    else
      @mangas = Manga.all
    end
  end

  def show
    @manga = Manga.find(params[:id])
    @chapitres = @manga.chapitres
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MangaMemo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/navbar" %>
  </body>
</html>

app/views/lectures/create.html.erb
<h1>Lectures#create</h1>
<p>Find me in app/views/lectures/create.html.erb</p>

app/views/lectures/destroy.html.erb
<h1>Lectures#destroy</h1>
<p>Find me in app/views/lectures/destroy.html.erb</p>

app/views/mangas/index.html.erb
<h1>Mangas#index</h1>
<div class="container mt-5 text-center">
    <%= form_with url: mangas_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "input",
            placeholder: "Rechercher un manga par nom, par auteur..."
        %>
        <button class="loupe-index" type="submit">
          <i class="fa-solid fa-magnifying-glass fa-lg" style="color: #7f7f7f;"></i>
        </button>
    <% end %>
  </div>

<div class="cards">
  <% @mangas.each do |manga|%>
    <%= link_to manga_path(manga), class:"text-decoration-none", style:"color: inherit" do %>
      <% if manga.nom.present? && manga.synopsys.present? && manga.couverture.present? %>
        <div class="cards">
          <article class="information [ card ]">
          <img src="<%= manga.couverture %>" class="card-image" alt="...">
          <span class="tag"><%= manga.statut %></span>
            <h2 class="title"><%= manga.nom %></h2>
            <p class="info"><%= truncate(manga.synopsys, length: 100) %></p>
            <dl class="details">
              <div>
                <dt>Mangaka</dt>
                <dd><%= manga.auteur %></dd>
              </div>
              <div>
                <dt>Note</dt>
                <dd><%= manga.note_moyenne %></dd>
              </div>
            </dl>
          </article>
        </div>

      <% end %>
    <% end %>
  <% end %>
</div>

app/views/mangas/show.html.erb
 <div class="cover-container">
    <img class="cover-image" src="<%= @manga.couverture %>" alt="">
    <h2 class="name"><%= @manga.nom %></h2>
</div>

  <ul class="nav justify-content-center" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button style="margin-right: 90px;" class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">À PROPOS</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">CHAPITRES</button>
    </li>
  </ul>



  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="container p-3">
        <p><%= @manga.synopsys %></p>
        <div class="border-bottom"></div>
        <p><%= @manga.auteur %></p>
        <p><%= @manga.statut %></p>
        <p><%= @manga.note_moyenne %></p>
      </div>
    </div>

   <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
  <h3>Liste des Chapitres</h3>

  <% manga_cover_url = @manga.couverture %>

  <% @chapitres.each do |chapitre| %>
  <div class="container">
    <div class="card-chapitre">
      <img src="<%= @manga.couverture %>" alt="">
      <h5>Chapitre <%= chapitre.numero_chapitre %></h5>

      <% lecture = current_user.lectures.find_by(chapitre_id: chapitre.id) %>
      <% if lecture.present? %>
        <% if lecture.lu %>
          <%= link_to "Marquer comme non lu","#", method: :post %>
        <% else %>
          <%= link_to "Marquer comme lu", "#", method: :post %>
        <% end %>
      <% else %>
        <%= link_to "Commencer la lecture", "#", method: :post %>
      <% end %>
    </div>
  </div>
<% end %>

</div>

app/views/pages/home.html.erb
          <% if user_signed_in? %>
            <%= link_to "Voir les manags", mangas_path, class: ""%>
          <% else %>
            <%= link_to "S'inscrire", new_user_registration_path, class:"btn-text-noir" %>
            <%= link_to "Se connecter", user_session_path, class:"btn-text-blanc" %>
          <% end %>
        </div>
      </div>
    </div>
<br>
  <div class="container">
    <div class="container mt-3 text-center">
      <%= form_with url: "/", method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "input",
              placeholder: "Rechercher un parc par nom, par ville..."
          %>
          <button class="loupe" type="submit">
            <i class="fa-solid fa-magnifying-glass fa-lg" style="color: #7f7f7f;"></i>
          </button>
      <% end %>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <ul class="navbar-nav mx-auto">
      <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa-solid fa-house fa-lg <%= 'active-icon' if current_page?(root_path) %>" ></i>
          <% end %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(mangas_path) %>">
          <%= link_to mangas_path, class: "navbar-brand" do %>
            <i class="fa-solid fa-list fa-lg <%= 'active-icon' if current_page?(mangas_path) %>" ></i>
          <% end %>
        </li>
        
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>